# noqa
"""initial schema

Revision ID: d787fbff17d9
Revises: 
Create Date: 2026-07-05 11:46:34.532313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd787fbff17d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('args_hash', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcp_audit_agent', 'mcp_audit', ['agent_id'], unique=False)
    op.create_index('ix_mcp_audit_owner', 'mcp_audit', ['owner_id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('default_currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_agent', 'activity_events', ['agent_id'], unique=False)
    op.create_index('ix_activity_owner_occurred', 'activity_events', ['owner_id', 'occurred_at'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('balances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('holder_type', sa.String(), nullable=False),
    sa.Column('holder_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('available', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('pending_out', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holder_type', 'holder_id', name='uq_balances_holder')
    )
    op.create_index(op.f('ix_balances_owner_id'), 'balances', ['owner_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('destination', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_actor_type', sa.String(), nullable=False),
    sa.Column('created_by_actor_id', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_counterparties_owner', 'counterparties', ['owner_id'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('holder_type', sa.String(), nullable=False),
    sa.Column('holder_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holder_type', 'holder_id', 'currency', name='uq_ledger_accounts_holder')
    )
    op.create_index(op.f('ix_ledger_accounts_owner_id'), 'ledger_accounts', ['owner_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('previous_secret_hash', sa.String(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_endpoints_owner', 'webhook_endpoints', ['owner_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_agent', 'approvals', ['agent_id'], unique=False)
    op.create_index('ix_approvals_owner', 'approvals', ['owner_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cards_agent', 'cards', ['agent_id'], unique=False)
    op.create_index('ix_cards_owner', 'cards', ['owner_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_credentials_agent_id'), 'credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credentials_owner_id'), 'credentials', ['owner_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('journal_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index('ix_ledger_entries_journal', 'ledger_entries', ['journal_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_policies_agent_version')
    )
    op.create_index('ix_policies_owner', 'policies', ['owner_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('source_currency', sa.String(), nullable=False),
    sa.Column('destination_amount', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('destination_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_arrival', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_agent_id'), 'quotes', ['agent_id'], unique=False)
    op.create_index('ix_quotes_owner', 'quotes', ['owner_id'], unique=False)
    op.create_table('virtual_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_identifier', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('supported_rails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_virtual_accounts_agent', 'virtual_accounts', ['agent_id'], unique=False)
    op.create_index('ix_virtual_accounts_owner', 'virtual_accounts', ['owner_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'key', name='uq_idempotency_credential_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('counterparty_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('source_amount', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('source_currency', sa.String(), nullable=False),
    sa.Column('destination_amount', sa.Numeric(precision=38, scale=9), nullable=True),
    sa.Column('destination_currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('rail', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_agent', 'payments', ['agent_id'], unique=False)
    op.create_index('ix_payments_owner', 'payments', ['owner_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('source_holder_type', sa.String(), nullable=False),
    sa.Column('source_holder_id', sa.String(), nullable=False),
    sa.Column('destination_holder_type', sa.String(), nullable=False),
    sa.Column('destination_holder_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=9), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfers_owner', 'transfers', ['owner_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement at the database level: ledger, audit, and policy
    # rows can never be updated or deleted. This is a binding constraint
    # (CLAUDE.md #2/#5), not an application-layer convention.
    op.execute(
        """
        CREATE FUNCTION enos_reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not permitted', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'raise_exception';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("ledger_entries", "activity_events", "mcp_audit", "policies"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION enos_reject_mutation();
            """
        )


def downgrade() -> None:
    for table in ("ledger_entries", "activity_events", "mcp_audit", "policies"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS enos_reject_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfers_owner', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_payments_owner', table_name='payments')
    op.drop_index('ix_payments_agent', table_name='payments')
    op.drop_table('payments')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_virtual_accounts_owner', table_name='virtual_accounts')
    op.drop_index('ix_virtual_accounts_agent', table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    op.drop_index('ix_quotes_owner', table_name='quotes')
    op.drop_index(op.f('ix_quotes_agent_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_policies_owner', table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_ledger_entries_journal', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_credentials_owner_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_agent_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_cards_owner', table_name='cards')
    op.drop_index('ix_cards_agent', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_approvals_owner', table_name='approvals')
    op.drop_index('ix_approvals_agent', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_webhook_endpoints_owner', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_ledger_accounts_owner_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index('ix_counterparties_owner', table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_balances_owner_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_activity_owner_occurred', table_name='activity_events')
    op.drop_index('ix_activity_agent', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_table('owners')
    op.drop_index('ix_mcp_audit_owner', table_name='mcp_audit')
    op.drop_index('ix_mcp_audit_agent', table_name='mcp_audit')
    op.drop_table('mcp_audit')
    # ### end Alembic commands ###
